djnci/urls.py
"""djnci URL Configuration."""

import os
from distutils.util import strtobool

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static, serve
from django.contrib import admin
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic.base import TemplateView

from graphene_django.views import GraphQLView

from django.views.decorators.csrf import csrf_exempt

ENABLE_GRAPHIQL = strtobool(os.getenv('DJNCI_GRAPHIQL', 'false'))


def template(template_name):
    """Reusable TemplateView to keep things shorter down below."""
    return ensure_csrf_cookie(TemplateView.as_view(template_name=template_name))


urlpatterns = [
    url(r'^$', template(template_name='index.html')),
    url(r'^graphql', csrf_exempt(GraphQLView.as_view(graphiql=ENABLE_GRAPHIQL))),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^a/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT,}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
    url(r'^.*/$', template(template_name='index.html')),
]

accounts/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import uuid
from gettext import gettext as _
from nameparser import HumanName

import usaddress
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.core.validators import FileExtensionValidator
from django.utils.deconstruct import deconstructible

from .managers import AccountProfileManager
from djnci.utils import path_and_rename


class AccountProfile(AbstractBaseUser, PermissionsMixin):

    CLASSROOM_CHOICES = (
        (1, 'Children\'s house'),
        (2, 'Lower Elementary'),
        (3, 'Upper Elementary'),
        (4, 'Adolescent')
    )

    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
        db_index=True
    )

    name = models.CharField(_('School, Business or Full Name'), max_length=255, blank=True)
    slug = models.SlugField(max_length=140, blank=True)

    phone = models.CharField(max_length=30, blank=True)
    title = models.CharField(max_length=75, blank=True)
    bio = models.TextField(_('Profile Bio'), blank=True)

    profile_photo = models.ImageField(_('Profile Photo'), upload_to='contact-photos', blank=True)
    profile_icon = models.ImageField(_('Profile Icon'), upload_to='contact-icons', blank=True)

    stripe_customer_id = models.CharField(_('Stripe Customer ID'), blank=True, max_length=255)

    ACCOUNT_TYPE_CHOICES = (
        ('parent', 'Parent/Guardian'),
        ('teacher', 'Teacher'),
        ('school', 'School'),
        ('ee-staff', 'EE Staff'),
    )
    account_type = models.CharField(_('Account Type'), blank=True, null=True, max_length=25, choices=ACCOUNT_TYPE_CHOICES)
    classroom = models.IntegerField(
        _('Classroom'),
        blank=True,
        null=True,
        choices=CLASSROOM_CHOICES, 
        help_text=_('If this user is a Teacher or affilated with one of their schools classrooms, which is it?')
    )

    assoc_location_list = models.ManyToManyField('locations.Location', blank=True, related_name='contact_assoc_location_list')
    assoc_school_list = models.ManyToManyField('accounts.School', blank=True, related_name='account_assoc_school_list')

    # Legacy MontessoriNCI DB Fields
    legacy_user_id = models.IntegerField(_('User ID (Legacy Portal)'), blank=True, null=True)
    legacy_username = models.CharField(_('Username (Legacy Portal)'), blank=True, max_length=75)
    legacy_school_id = models.IntegerField(_('School ID (Legacy Portal)'), blank=True, null=True)
    legacy_contact = models.CharField(_('Contact Name (Legacy Portal)'), blank=True, max_length=75)

    guid = models.CharField(max_length=140, blank=True)
    rank = models.IntegerField(_('Sort order'), blank=True, null=True)

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active.'
            'Unselect this instead of deleting accounts.'
        )
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.')
    )
    is_superuser = models.BooleanField(
        _('superuser'),
        default=False,
        help_text=_(
            'Designates that this user has all permissions without explicitly assigning them.'
        )
    )

    date_joined = models.DateTimeField(default=timezone.now, null=True)
    modified = models.DateTimeField(blank=True, auto_now=True)

    username = models.CharField(blank=True, max_length=30, verbose_name='username')
    first_name = models.CharField(blank=True, max_length=30, verbose_name='first name')
    last_name = models.CharField(blank=True, max_length=30, verbose_name='last name')

    USERNAME_FIELD = 'email'

    objects = AccountProfileManager()

    class Meta:
        verbose_name = _('Account Profile')
        verbose_name_plural = _('Account Profiles')

    def __str__(self):
        if self.name:
            return '%s (%s)' % (self.name, self.email)
        return self.email

    def get_full_name(self):
        return self.email

    def get_first_name(self):
        i = HumanName(self.name)
        if i.first:
            return i.first.capitalize()
        return None

    def get_last_name(self):
        i = HumanName(self.name)
        if i.last:
            return i.last.capitalize()
        return None

    def get_short_name(self):
        return self.email

    def is_nci_montessori(self):
        # id '50' = Nature's Classroom Montessori (Mukwonago)
        if self.assoc_school_list.filter(id=50):
            return True
        return False

    def save(self, *args, **kwargs):
        if not self.guid:
            self.guid = str(uuid.uuid4())
        self.slug = slugify(self.name)
        super(AccountProfile, self).save(*args, **kwargs)


class AccountProfileAddress(models.Model):
    """Address to get in touch with Contacts."""

    street_address = models.TextField(_('Street Address'))
    contact = models.ForeignKey(AccountProfile)
    is_billing = models.BooleanField(default=False)

    created = models.DateTimeField(editable=False, auto_now_add=True)
    modified = models.DateTimeField(blank=True, auto_now=True)

    class Meta:
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

    def get_address_city(self):
        return usaddress.tag(self.street_address)[0]['PlaceName']

    def get_address_state(self):
        return usaddress.tag(self.street_address)[0]['StateName']

    def __str__(self):
        return self.street_address


class School(models.Model):

    SCHOOL_TYPE_CHOICES = (
        ('public', 'Public School'),
        ('montessori', 'Montessori School')
    )

    name = models.CharField(_('Name of School'), max_length=140)
    slug = models.SlugField(max_length=140, blank=True)

    phone = models.CharField(max_length=30, blank=True)

    school_type = models.CharField(choices=SCHOOL_TYPE_CHOICES, default="public", max_length=15)

    # Legacy MontessoriNCI DB Fields
    legacy_school_id = models.IntegerField(_('School ID (Legacy Portal)'), blank=True, null=True)
    legacy_contact = models.CharField(_('Contact Name (Legacy Portal)'), blank=True, max_length=75)

    email_whitelist = models.TextField(
        _('Email Whitelist'),
        blank=True,
        help_text=_('Comma-separated list of teacher email addresses pre-approved to access this school.')
    )

    guid = models.CharField(max_length=140)
    is_active = models.BooleanField(default=True)

    created = models.DateTimeField(editable=False, auto_now_add=True)
    modified = models.DateTimeField(blank=True, auto_now=True)

    class Meta:
        verbose_name = _('School')
        verbose_name_plural = _('Schools')
        ordering = ['name', ]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.guid:
            self.guid = str(uuid.uuid4())
        self.slug = slugify(self.name)
        super(School, self).save(*args, **kwargs)


class SchoolAddress(models.Model):
    """Address to get in touch with Contacts."""

    street_address = models.TextField(_('Street Address'))
    school = models.ForeignKey(School)

    created = models.DateTimeField(editable=False, auto_now_add=True)
    modified = models.DateTimeField(blank=True, auto_now=True)

    class Meta:
        verbose_name = _('School Address')
        verbose_name_plural = _('School Addresses')

    def get_address_city(self):
        return usaddress.tag(self.street_address)[0]['PlaceName']

    def get_address_state(self):
        return usaddress.tag(self.street_address)[0]['StateName']

    def __str__(self):
        return self.street_address


class SchoolNote(models.Model):
    """Notes attached to a School."""

    school = models.ForeignKey(School)
    author = models.ForeignKey('accounts.AccountProfile', verbose_name='Author of note', blank=True, null=True)

    NOTE_TYPE_CHOICES = (
        (0, 'General'),
        (1, 'Billing & Payments'),
        (2, 'Phone call')
    )
    note_type = models.IntegerField(
        blank=True, null=True, choices=NOTE_TYPE_CHOICES, default=0
    )

    message = models.TextField(blank=True)

    guid = models.CharField(max_length=140, blank=True)
    created = models.DateTimeField(editable=False, auto_now_add=True)
    modified = models.DateTimeField(blank=True, auto_now=True)

    class Meta:
        verbose_name = _('School Note')
        verbose_name_plural = _('School Notes')

    def __str__(self):
        return 'Note for %s' % self.school

    def get_short_guid(self):
        return self.guid[:5]

    def save(self, *args, **kwargs):
        if not self.guid:
            self.guid = str(uuid.uuid4())
        super(SchoolNote, self).save(*args, **kwargs)


class SchoolFile(models.Model):
    """File attached to a School."""

    PUBLIC_CHOICES = (
        (0, 'Private'),
        (1, 'Public'),
    )

    school = models.ForeignKey(School, related_name='school_files', on_delete=models.CASCADE)
    file = models.FileField(upload_to=path_and_rename, validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])
    file_name = models.CharField(max_length=140, blank=False, default='')
    is_public = models.IntegerField(blank=False, default=0, choices=PUBLIC_CHOICES)

    class Meta:
        verbose_name = _('School File')
        verbose_name_plural = _('School Files')

    def __str__(self):
        return 'File for %s' % self.school

    def save(self, *args, **kwargs):
        super(SchoolFile, self).save(*args, **kwargs)



class Insurance(models.Model):
    company_name = models.CharField(_('Name of Insurance Company'), max_length=75, blank=True)
    policy_num = models.CharField(_('Policy #'), max_length=25, blank=True)

accounts/forms.py
from django import forms

from .models import SchoolFile

class SchoolFileUploadForm(forms.ModelForm):

    class Meta:
        model = SchoolFile
        fields = '__all__'

accounts/templates/base_email.html
<html>
  <body>

    <div style="margin: auto; width: 73%; min-width: 420px; max-width: 740px; border-radius: 4px; padding: 20px 20px 10px 20px; border: 1px solid #dadada; font-family: sans-serif;">

      <img src="https://app.discovernci.org/logo.png" target="_blank" width="64" style="width: 64px;" />

      <h2 style="margin-top: 10px;">{% block title %}{% endblock %}</h2>

      {% block body %}{% endblock %}

    </div>

    <div style="margin: auto; width: 73%; min-width: 420px;  max-width: 740px; padding: 10px 20px; font-family: sans-serif;">
      <p style="line-height: 1.4em; font-size: 13px; color: #a3a3a3; font-family: sans-serif;">Nature's Classroom Institute and Montessori School • est. 1995
        <br />Learning through experience. Growing through expression.
        <br />https://discovernci.org • info@nciw.org • (262) 363-2815</p>
      <p>
        <a
          href="https://www.facebook.com/NaturesClassroomInstitute/"
          target="_blank"
          rel="noopener noreferrer"
          style="margin-left: 15px; color: #5bb3ff;"
        >
          <i class="fas fa-user"></i>Like us on Facebook
        </a>
        &nbsp;&nbsp;
        <a
          href="https://www.instagram.com/naturesclassroominstitute/"
          target="_blank"
          rel="noopener noreferrer"
          style="margin-left: 15px; color: #5bb3ff;"
        >
          Follow us on Instagram
        </a>
      </p>
    </div>

  </body>
</html>

accounts/templates/email_fieldtrip_registration_confirmation.html
{% extends "base_email.html" %}

{% block title %}NCI Field Trip Confirmation{% endblock title %}

{% block body %}

  <p>Hello, {{ account.name }}</p>

  <p><strong>{{ student.name }}</strong> has been registered to attend a field trip to Nature's Classroom Institute.</p>

  <ul>
    <li><strong>Name</strong>: {{ student.name }}</li>
    <li><strong>School</strong>: {{ school.name }}</li>
    <li><strong>Classroom</strong>: {{ student.get_classroom_display }}</li>
    <li><strong>Field Trip</strong>: {{ fieldtrip.name }}</li>
    <li><strong>Start Date</strong>: {{ fieldtrip.start_date }}</li>
    <li><strong>End Date</strong>: {{ fieldtrip.end_date }}</li>
  </ul>
  
{% endblock body %}

accounts/templates/email_password_reset.html
{% extends "base_email.html" %}

{% block title %}Password Reset{% endblock title %}

{% block body %}

  <p>Hey {{ account.name }}, Someone, presumably you, just initiated a password reset on discovernci.org. If this comes as news to you you can safely ignore this email and we'll keep your account safe.</p>

  <p>Reset your password by going to: {{ link }}</p>
  
{% endblock body %}

accounts/templates/email_staff_new_teacher_account.html
{% extends "base_email.html" %}

{% block title %}New NCI Teacher Account{% endblock title %}

{% block body %}

  <p>{{ account.name }}, a Teacher from {{ school.name }} has just created an account on discovernci.org. If this seems right to you, you must approve their account. They will not be able to sign in until you do. If this looks suspicious you can either safely ignore this request{% if shcool.phone %} or follow up with the school by reaching them at {{ shcool.phone }}{% endif %}.</p>

  <ul>
    <li> {{ school.name }} </li>
    <li> <strong>{{ account.name }}</strong> </li>
    <li> {{ account.email }} </li>
    {% if phone %}
      <li> {{ account.phone }} </li>
    {% endif %}
  </ul>

  <a href="https://app.discovernci.org/approve/{{ account.guid}}/{{school.guid}}" style="width: 200px; text-align: center; text-decoration: none; border-radius: 4px; margin: 20px 0px; padding: 10px 20px; display: inline-block; white-space: nowrap; background: #16b55f; color: #fff; font-size: 110%;">Approve Teacher</a>

  <p>If you have admin access you can adjust this accounts details at:
      <br />https://app.discovernci.org/a/accounts/accountprofile/{{ account.id }}/change/</p>

{% endblock body %}

accounts/templates/email_staff_new_whitelisted_teacher_account.html
{% extends "base_email.html" %}

{% block title %}New NCI Teacher Account{% endblock title %}

{% block body %}

  <p>{{ account.name }}, a Teacher from {{ school.name }} has just created an account on discovernci.org. Their email address ({{ account.email }}) was listed in {{ school.name }}'s email whitelist and so their account was automatically activated. There is no action necessary, this is just a heads-up that they created their account.</p>

  <ul>
    <li>Name: <strong>{{ account.name }}</strong></li>
    <li>Email: {{ account.email }}</li>
    {% if phone %}<li>Phone: {{ account.phone }}</li>{% endif %}
    <li>Date Joined: {{ account.date_joined }}</li>
    <li>School: <strong>{{ school.name }}</strong></li>
  </ul>

  <p>If you have admin access you can adjust this accounts details at:
      <br />https://app.discovernci.org/a/accounts/accountprofile/{{ account.id }}/change/.</p>

  <p>You can review {{ school.name }}'s settings, including their email whitelist at:
      <br />https://app.discovernci.org/a/accounts/school/{{ school.id }}/change/</p>
      
{% endblock body %}

accounts/templates/email_staff_tech_support.html
{% extends "base_email.html" %}

{% block title %}Technical Support Message{% endblock title %}

{% block body %}

  <p>We just received a technical support inquiry from the following {{ account.account_type }}:</p>

  <ul>
    <li><strong>Name</strong>: {{ account.name }}</li>
    <li><strong>Email</strong>: {{ account.email }}</li>
    <li><strong>Message</strong>: </li> {{ message }}
  </ul>

  <p>You can access {{ account.name }}'s account settings by going to
    <br />https://app.discovernci.org/a/accounts/accountprofile/{{ account.id }}/change/</p>
    
{% endblock body %}

accounts/templates/email_stripe_receipt.html
{% extends "base_email.html" %}

{% block title %}Thank you for your Donation!{% endblock title %}

{% block body %}

  <p>Receipt ID: {{ receipt_id }}</p>

  <p>
    Thank you for your generous donation of ${{ amount }}.
    Nature’s Classroom Institute and Montessori School is a not-for-profit organization that expands the educational scope of children beyond the classroom through an authentic Montessori education and a strong outdoors program.
    We provide a tangible experience that encourages the growth of local children through academics, the environment, and community awareness to achieve a holistic educational experience.
  </p>
  <p>
    We greatly appreciate your support to further our mission to develop self-motivated, responsible, compassionate, independent problem solvers, who sustain a lifelong love of learning through an experiential education based in and around the natural world.
    For your tax purposes, we are a 501(c)(3) charity and our tax ID number is 46-4732782.
  </p>

{% endblock body %}

accounts/templates/email_tech_support.html
{% extends "base_email.html" %}

{% block title %}Technical Support Message{% endblock title %}

{% block body %}

  <p>Hello, {{ account.name }}</p>

  <p>We received your technical support inquiry and just moments ago send a notification to our technical support team.</p>

{% endblock body %}

accounts/templates/email_welcome_approved_teacher.html
{% extends "base_email.html" %}

{% block title %}Your account has been activated{% endblock title %}

{% block body %}

  <p>You're {{ account.account_type }} account on discovernci.org has been activated. You can now sign in and manage your student records.</p>

  <a href="https://app.discovernci.org/login" style="width: 200px; text-align: center; text-decoration: none; border-radius: 4px; margin: 20px 0px; padding: 10px 20px; display: inline-block; white-space: nowrap; background: #16b55f; color: #fff; font-size: 110%;">Sign in</a>

{% endblock body %}

accounts/templates/email_welcome_new_signup.html
{% extends "base_email.html" %}

{% block title %}Welcome to Nature's Classroom Institute{% endblock title %}

{% block body %}

  <p>You've successfully signed up as a {{ account.account_type }} on discovernci.org.</p>

  <ul>
    <li>Name: <strong>{{ account.name }}</strong></li>
    <li>Account Type: <strong>{{ account.account_type|capfirst }}</strong> {% if not account.is_active %}<i>Pending Approval</i>{% endif %}</li>
    <li>School: <strong>{{ school.name }}</strong>{% if school.phone %} ({{ school.phone }}){% endif %}</li>
    <li>Date Joined: <strong>{{ account.date_joined }}</strong></li>
  </ul>

  {% if account.account_type == 'teacher' and not account.is_active %}
    <p>NOTE: With your students safety in mind, Your account must first be verified before you can sign in. This verification process can take up to 24-hours.</p>
  {% elif account.account_type == 'parent' %}
    <p>Sign in to update and manage your child(ren)'s NCI experience including food preferences, medications, and more.</p>
    <a href="https://app.discovernci.org/login" style="width: 200px; text-align: center; text-decoration: none; border-radius: 4px; margin: 20px 0px; padding: 10px 20px; display: inline-block; white-space: nowrap; background: #16b55f; color: #fff; font-size: 110%;">Sign in</a>
  {% endif %}

{% endblock body %}